package main

import (
	"fmt"
	"loca/src/config"
	"os"
	"path/filepath"

	ignore "github.com/sabhiram/go-gitignore"
)

func main() {
	root, _ := os.Getwd()

	var ig *ignore.GitIgnore
	if _, err := os.Stat(".gitignore"); err == nil {
		ig, _ = ignore.CompileIgnoreFile(".gitignore")
	}

	total := 0

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		rel, _ := filepath.Rel(root, path)

		if ig != nil && ig.MatchesPath(rel) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}

		if d.IsDir() && d.Name() == "node_modules" {
			return filepath.SkipDir
		}

		if config.AutoGenerated[d.Name()] {
			return nil
		}

		if !d.IsDir() && config.CodeExtensions[filepath.Ext(d.Name())] {
			lines := countLines(path)
			total += lines
		}

		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error walking directory: %v\n", err)
		return
	}

	fmt.Printf("\n📊 Total lignes de code humain : %d\n\n", total)
}
